includes: []
production:
  private:
    libraries: []
  public:
    libraries:
      # - name: Zefiros-Software/Boost
      #   version: ^1.6.9
      - name: Zefiros-Software/GoogleTest
        version: ^1.0.0