language: node_js
node_js:
  - "12"
cache:
  yarn: true
install:
  - yarn install
script:
  - yarn build
  - yarn lint
  - yarn test
after_success:
  - yarn package

deploy:
  provider: npm
  email: p.e.visscher@zefiros.io
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: zpmpkg/zpm
    branch: alpha
