registries:
  # - url: 'https://github.com/zpmpkg/registry.git'
  #   branch: 'master'
  - path: $ZPM/registry
registry:
  - name: libraries
  - name: extractor
    options:
      singular: true
      schema: $ZPM/extractors/extractor.v1.json
      defaults:
        libraries:
          name: ZPM
          path: extractors/default
  - name: builder
    options:
      singular: true
      defaults:
        libraries:
          name: ZPM
          path: builder/default
