registries:
  # - url: 'https://github.com/zpmpkg/registry.git'
  #   branch: 'master'
  - path: $ZPM/registry
registry:
  - name: extractor
    options:
      isBuildDefinition: true
      schema: $ZPM/extractor/extractor.v1.json
      settingsPath: extract
      defaults:
        libraries:
          name: ZPM
          path: extractor/default
  - name: builder
    options:
      isBuildDefinition: true
      settingsPath: build
      defaults:
        libraries:
          name: ZPM
          path: builder/default
  - name: libraries
