registries:
  # - url: 'https://github.com/zpmpkg/registry.git'
  #   branch: 'master'
  - path: $ZPM/registry
registry:
  - name: libraries
  - name: extractors
    options:
      schema: $ZPM/extractors/extractor.v1.json
  - name: builders
