registries:
  # - url: 'https://github.com/zpmpkg/registry.git'
  #   branch: 'master'
  - url: manifest
registry:
  - name: libraries
  - name: extractors
    options:
      schema: extractors/extractor.v1.json
  - name: builders
