registries: 
  # - url: 'https://github.com/zpmpkg/registry.git'
  #   branch: 'master'
  - name: ZPM
    path: $ZPM/registry
    workingDirectory: $ZPM
registry:
  - name: extractor
    options:
      isBuildDefinition: true
      schema: $ZPM/extractor/extractor.v1.json
      settingsPath: extract
      defaults:
        libraries:
          name: ZPM:extractor/default
  - name: builder
    options:
      isBuildDefinition: true
      settingsPath: build
      defaults:
        libraries:
          name: ZPM:builder/default
  - name: libraries
