/** Declaration file generated by dts-gen */

declare module 'appdirectory' {
    export = appdirectory
    class appdirectory {
        constructor(options: any)

        userCache(): string

        userConfig(): string

        userData(): string

        userLogs(): string
    }
}
