/** Declaration file generated by dts-gen */

export = ora;

declare function ora(opts: any): any;

declare namespace ora {
    const prototype: {
    };

    function promise(action: any, options: any): any;

}

