includes: []
requires:
  libraries:
    #- name: Zefiros-Software/Boost
    #  version: ^1.6.9
    - name: Zefiros-Software/The-Forge
      version: ^1.8.0
      # prevent this
      ##- path: ../
    #- name: Zefiros-Software/GoogleTest
    #  version: ^1.7.0
    - path: sandbox3
      settings: 
        wooo: fooo
    #- path: ../sandbox2/sandbox3