includes: []
production:
  libraries:
    #- name: Zefiros-Software/Boost
    #  version: ^1.6.9
    - name: Zefiros-Software/The-Forge
      version: ^1.8.0 <1.9.0
    #- name: Zefiros-Software/GoogleTest
    #  version: ^1.7.0