/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DefinitionsSchema {
    [k: string]: any
}
/**
 * This interface was referenced by `DefinitionsSchema`'s JSON-Schema
 * via the `definition` "Registry".
 */
export interface Registry {
    url: string
    branch?: string
}
/**
 * This interface was referenced by `DefinitionsSchema`'s JSON-Schema
 * via the `definition` "Entry".
 */
export interface Entry {
    name: string
    repository: string
    definition?: string
}
