function(zpm_defaults)
  set_property(GLOBAL PROPERTY USE_FOLDERS ON)

  set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib PARENT_SCOPE)
  set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib PARENT_SCOPE)
  set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin PARENT_SCOPE)

  set(CMAKE_TESTING_ENABLED ON PARENT_SCOPE)
  set(ZPM_LOADED ON PARENT_SCOPE)
endfunction()
